version: '3'
services:

  frontend:
    build: frontend/
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: always
    volumes:
      - ./logs:/var/log/frontend
    networks:
      - rede-virtual-1

  backend:
    build: backend/
    ports:
      - 3001:3001
    environment:
      - DB_HOST=database
    depends_on:
      - database
    restart: always
    networks:
      - rede-virtual-1
      - rede-virtual-2

  database:
    image: betrybe/docker-compose-example-database:v1
    restart: always
    volumes:
      - dados-do-banco:/data/db
    networks:
      - rede-virtual-2

volumes:
  dados-do-banco:

networks:
  rede-virtual-1:
  rede-virtual-2:
